#+Title: About
#+Summary: Homepage
#+URL: index.html
#+Save_as: index.html
#+Sortorder: 010
#+Slug: home
#+OPTIONS: toc:nil num:nil html-postamble:nil

*Restriction site associated DNA markers* (RAD tags) are used in association
with high-throughput sequencing methods for *genotyping in both model and
non-model organisms*.

RAD tags are produced by using *restriction enzymes* to cut an organism DNA and
to perform a *genome complexity reduction*: only fragments associated with
restriction sites are sequenced. The distribution of sequenced fragments along
the genome can be adjusted by carefully choosing the restriction enzyme.

* RAD tag course in Roscoff, March 2015

The local organizers of the course are Thomas Broquet and Didier Jollivet. The
course will be taught by Matthieu Bruneaux and Gildas Le Corguillé.

All the materials are available from [[https://github.com/mdjbru-teaching-material/roscoff-RAD-tags-course-2015][GitHub]].

* Contact

Comments, questions and suggestions can be sent to 
<a href="mailto:matthieu.d.bruneaux@jyu.fi">Matthieu Bruneaux</a>.
