#+Title: About
#+Summary: Homepage
#+URL: index.html
#+Save_as: index.html
#+Sortorder: 010
#+Slug: home
#+OPTIONS: toc:nil num:nil html-postamble:nil

*Restriction site associated DNA markers* (RAD markers or RAD tags) are used in
association with high-throughput sequencing methods for *genotyping in both
model and non-model organisms*.

RAD tags are produced by using *restriction enzymes* to cut an organism DNA and
to perform a *genome complexity reduction*. In a RAD-seq experiment, only those
fragments associated with restriction sites are sequenced. The distribution of
sequenced fragments along the genome can be adjusted by carefully choosing the
restriction enzymes.

* RAD tag course in Roscoff, March 2015

The local organizers of the course are Thomas Broquet and Didier Jollivet. The
course will be taught by Matthieu Bruneaux and Gildas Le Corguillé.

All the materials are available from [[https://github.com/mdjbru-teaching-material/roscoff-RAD-tags-course-2015][GitHub]].

* Before the course

Please fill the pre-assessment form that can be found [[file:resources/pre-assessment.txt][here]] and send it back to
Matthieu Bruneaux ([[mailto:matthieu.d.bruneaux@jyu.fi][matthieu.d.bruneaux@jyu.fi]]).

* Schedule

The practicals will take place on 10th, 11th and 12th of March at the [[http://www.sb-roscoff.fr/][Station
Biologique de Roscoff]], in the computer room (IGM).

- *2015-03-10 Tue (Afternoon)*: RAD-seq presentation, beginning of practicals
- *2015-03-11 Wed (All day)*: Practicals and open questions
- *2015-03-12 Thu (All day)*: Practicals and open questions, conclusion

* RAD-seq presentation

The pdf file of the presentation can be found [[file:resources/presentation.pdf][here]] (work in progress).

* Contact

Comments, questions and suggestions can be sent to [[mailto:matthieu.d.bruneaux@jyu.fi][Matthieu Bruneaux]].
